# Generated by Django 4.2.16 on 2024-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('doctor', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('appointment_type', models.CharField(max_length=20)),
                ('booking', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
